=== mackymiro/tpccr-project/xmlparser/parser/camp/dtd/config/text-to-entity-replacement-map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="entities">
		<xs:annotation>
			<xs:documentation>root element for text to entity replacements</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="entity">
					<xs:annotation>
						<xs:documentation>A text to entity pairing</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="key" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>the entity's name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="type" use="required">
							<xs:annotation>
								<xs:documentation>the type of entiity</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="characterEntity"/>
									<xs:enumeration value="piEntity"/>
									<xs:enumeration value="stringEntity"/>
									<xs:enumeration value="tagEntity"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="value" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>the entity's replacement value</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mackymiro/tpccr-project/xmlparser/parser/camp/dtd_06172017/content/lego-entity-map.xml
<?xml version="1.0" encoding="UTF-8"?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/camp/dtd/config/text-to-entity-replacement-map.xsd">

	<entity value="amalg" key="2210" type="characterEntity"/>
	<entity value="Barwed" key="2306" type="characterEntity"/>
	<entity value="barwed" key="22BC" type="characterEntity"/>
	<entity value="Cap" key="22D2" type="characterEntity"/>
	<entity value="Cup" key="22D3" type="characterEntity"/>
	<entity value="cuvee" key="22CE" type="characterEntity"/>
	<entity value="cuwed" key="22CF" type="characterEntity"/>
	<entity value="diam" key="22C4" type="characterEntity"/>
	<entity value="divonx" key="22C7" type="characterEntity"/>
	<entity value="intcal" key="22BA" type="characterEntity"/>
	<entity value="lthree" key="22CB" type="characterEntity"/>
	<entity value="ltimes" key="22C9" type="characterEntity"/>
	<entity value="minusb" key="229F" type="characterEntity"/>
	<entity value="oast" key="229B" type="characterEntity"/>
	<entity value="ocir" key="229A" type="characterEntity"/>
	<entity value="odash" key="229D" type="characterEntity"/>
	<entity value="odot" key="2299" type="characterEntity"/>
	<entity value="ominus" key="2296" type="characterEntity"/>
	<entity value="oplus" key="2295" type="characterEntity"/>
	<entity value="osol" key="2298" type="characterEntity"/>
	<entity value="otimes" key="2297" type="characterEntity"/>
	<entity value="plusb" key="229E" type="characterEntity"/>
	<entity value="plusdo" key="2214" type="characterEntity"/>
	<entity value="rthree" key="22CC" type="characterEntity"/>
	<entity value="rtimes" key="22CA" type="characterEntity"/>
	<entity value="sdot" key="22C5" type="characterEntity"/>
	<entity value="sdotb" key="22A1" type="characterEntity"/>
	<entity value="setmn" key="2216" type="characterEntity"/>
	<entity value="sqcap" key="2293" type="characterEntity"/>
	<entity value="sqcup" key="2294" type="characterEntity"/>
	<entity value="timesb" key="22A0" type="characterEntity"/>
	<entity value="top" key="22A4" type="characterEntity"/>
	<entity value="uplus" key="228E" type="characterEntity"/>
	<entity value="wreath" key="2240" type="characterEntity"/>
	<entity value="xdtri" key="25BD" type="characterEntity"/>
	<entity value="xutri" key="25B3" type="characterEntity"/>
	<entity value="prod" key="220F" type="characterEntity"/>
	<entity value="sum" key="2211" type="characterEntity"/>
	<entity value="ape" key="224A" type="characterEntity"/>
	<entity value="asymp" key="224D" type="characterEntity"/>
	<entity value="bcong" key="224C" type="characterEntity"/>
	<entity value="bepsi" key="220D" type="characterEntity"/>
	<entity value="bowtie" key="22C8" type="characterEntity"/>
	<entity value="bsim" key="223D" type="characterEntity"/>
	<entity value="bsime" key="22CD" type="characterEntity"/>
	<entity value="bump" key="224E" type="characterEntity"/>
	<entity value="bumpe" key="224F" type="characterEntity"/>
	<entity value="cire" key="2257" type="characterEntity"/>
	<entity value="colone" key="2254" type="characterEntity"/>
	<entity value="cuepr" key="22DE" type="characterEntity"/>
	<entity value="cuesc" key="22DF" type="characterEntity"/>
	<entity value="dashv" key="22A3" type="characterEntity"/>
	<entity value="ecir" key="2256" type="characterEntity"/>
	<entity value="ecolon" key="2255" type="characterEntity"/>
	<entity value="eDot" key="2251" type="characterEntity"/>
	<entity value="esdot" key="2250" type="characterEntity"/>
	<entity value="efDot" key="2252" type="characterEntity"/>
	<entity value="egs" key="22DD" type="characterEntity"/>
	<entity value="els" key="22DC" type="characterEntity"/>
	<entity value="erDot" key="2253" type="characterEntity"/>
	<entity value="fork" key="22D4" type="characterEntity"/>
	<entity value="frown" key="2322" type="characterEntity"/>
	<entity value="gap" key="2273" type="characterEntity"/>
	<entity value="gsdot" key="22D7" type="characterEntity"/>
	<entity value="gE" key="2267" type="characterEntity"/> 
	<entity value="gel" key="22DB" type="characterEntity"/>
	<entity value="Gg" key="22D9" type="characterEntity"/> 
	<entity value="gl" key="2277" type="characterEntity"/> 
	<entity value="Gt" key="226B" type="characterEntity"/> 
	<entity value="lap" key="2272" type="characterEntity"/>
	<entity value="ldot" key="22D6" type="characterEntity"/>
	<entity value="lE" key="2266" type="characterEntity"/> 
	<entity value="leg" key="22DA" type="characterEntity"/>
	<entity value="lg" key="2276" type="characterEntity"/> 
	<entity value="Ll" key="22D8" type="characterEntity"/> 
	<entity value="Lt" key="226A" type="characterEntity"/> 
	<entity value="ltrie" key="22B4" type="characterEntity"/>
	<entity value="mid" key="2223" type="characterEntity"/>
	<entity value="models" key="22A7" type="characterEntity"/>
	<entity value="pr" key="227A" type="characterEntity"/> 
	<entity value="pre" key="227C" type="characterEntity"/>
	<entity value="prsim" key="227E" type="characterEntity"/>
	<entity value="rtrie" key="22B5" type="characterEntity"/>
	<entity value="sc" key="227B" type="characterEntity"/> 
	<entity value="scap" key="227F" type="characterEntity"/>
	<entity value="sce" key="227D" type="characterEntity"/>
	<entity value="smid" key="E301" type="characterEntity"/>
	<entity value="smile" key="2323" type="characterEntity"/>
	<entity value="sqsub" key="228F" type="characterEntity"/>
	<entity value="sqsube" key="2291" type="characterEntity"/>
	<entity value="sqsup" key="2290" type="characterEntity"/>
	<entity value="sqsupe" key="2292" type="characterEntity"/>
	<entity value="Sub" key="22D0" type="characterEntity"/>
	<entity value="Sup" key="22D1" type="characterEntity"/>
	<entity value="trie" key="225C" type="characterEntity"/>
	<entity value="twixt" key="226C" type="characterEntity"/>
	<entity value="vdash" key="22A2" type="characterEntity"/>
	<entity value="Vdash" key="22A9" type="characterEntity"/>
	<entity value="vDash" key="22A8" type="characterEntity"/>
	<entity value="veebar" key="22BB" type="characterEntity"/>
	<entity value="vltri" key="22B2" type="characterEntity"/>
	<entity value="vrtri" key="22B3" type="characterEntity"/>
	<entity value="Vvdash" key="22AA" type="characterEntity"/>
	<entity value="acute" key="00B4" type="characterEntity"/>
	<entity value="breve" key="02D8" type="characterEntity"/>
	<entity value="caron" key="02C7" type="characterEntity"/>
	<entity value="cedil" key="00B8" type="characterEntity"/>
	<entity value="dblac" key="02DD" type="characterEntity"/>
	<entity value="dot" key="02D9" type="characterEntity"/>
	<entity value="grave" key="0060" type="characterEntity"/>
	<entity value="macr" key="00AF" type="characterEntity"/>
	<entity value="ogon" key="02DB" type="characterEntity"/>
	<entity value="ring" key="02DA" type="characterEntity"/>
	<entity value="tilde" key="02DC" type="characterEntity"/>
	<entity value="Agr" key="0391" type="characterEntity"/>
	<entity value="Bgr" key="0392" type="characterEntity"/>
	<entity value="Egr" key="0395" type="characterEntity"/>
	<entity value="Zgr" key="0396" type="characterEntity"/>
	<entity value="EEgr" key="0397" type="characterEntity"/>
	<entity value="Igr" key="0399" type="characterEntity"/>
	<entity value="Kgr" key="039A" type="characterEntity"/>
	<entity value="Mgr" key="039C" type="characterEntity"/>
	<entity value="Ngr" key="039D" type="characterEntity"/>
	<entity value="ogr" key="03BF" type="characterEntity"/>
	<entity value="Ogr" key="039F" type="characterEntity"/>
	<entity value="Rgr" key="03A1" type="characterEntity"/>
	<entity value="Tgr" key="03A4" type="characterEntity"/>
	<entity value="Ugr" key="03A5" type="characterEntity"/>
	<entity value="KHgr" key="03A7" type="characterEntity"/>
	<entity value="alpha" key="03B1" type="characterEntity"/>
	<entity value="beta" key="03B2" type="characterEntity"/>
	<entity value="gamma" key="03B3" type="characterEntity"/>
	<entity value="Gamma" key="0393" type="characterEntity"/>
	<entity value="gammad" key="03DC" type="characterEntity"/>
	<entity value="delta" key="03B4" type="characterEntity"/>
	<entity value="Delta" key="0394" type="characterEntity"/>
	<entity value="epsi" key="220A" type="characterEntity"/>
	<entity value="epsiv" key="03B5" type="characterEntity"/>
	<entity value="zeta" key="03B6" type="characterEntity"/>
	<entity value="eta" key="03B7" type="characterEntity"/>
	<entity value="thetas" key="03B8" type="characterEntity"/>
	<entity value="Theta" key="0398" type="characterEntity"/>
	<entity value="thetav" key="03D1" type="characterEntity"/>
	<entity value="iota" key="03B9" type="characterEntity"/>
	<entity value="kappa" key="03BA" type="characterEntity"/>
	<entity value="kappav" key="03F0" type="characterEntity"/>
	<entity value="lambda" key="03BB" type="characterEntity"/>
	<entity value="Lambda" key="039B" type="characterEntity"/>
	<entity value="mu" key="03BC" type="characterEntity"/> 
	<entity value="nu" key="03BD" type="characterEntity"/> 
	<entity value="xi" key="03BE" type="characterEntity"/> 
	<entity value="Xi" key="039E" type="characterEntity"/> 
	<entity value="pi" key="03C0" type="characterEntity"/> 
	<entity value="piv" key="03D6" type="characterEntity"/>
	<entity value="Pi" key="03A0" type="characterEntity"/> 
	<entity value="rho" key="03C1" type="characterEntity"/>
	<entity value="rhov" key="03F1" type="characterEntity"/>
	<entity value="sigma" key="03C3" type="characterEntity"/>
	<entity value="Sigma" key="03A3" type="characterEntity"/>
	<entity value="sigmav" key="03C2" type="characterEntity"/>
	<entity value="tau" key="03C4" type="characterEntity"/>
	<entity value="upsi" key="03C5" type="characterEntity"/>
	<entity value="Upsi" key="03D2" type="characterEntity"/>
	<entity value="phis" key="03C6" type="characterEntity"/>
	<entity value="Phi" key="03A6" type="characterEntity"/>
	<entity value="phiv" key="03D5" type="characterEntity"/>
	<entity value="chi" key="03C7" type="characterEntity"/>
	<entity value="psi" key="03C8" type="characterEntity"/>
